### ISSUE TITLE
[TCK] TSAuthConfigProviderServlet logger not initialized when used with vendor AuthConfigFactory

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/authentication#116]
The TCK user guide specifies there is 2 options to set up the TSSV.
1/ use the JVM wide configuration to load the TS AuthConfigFactory.
2/ use the AuthConfigFactory.register methods to register the provider

When using 2/, the TSAuthConfigFactory is not used and won't call the 3 args constructor on TSAuthConfigProviderServlet. See link bellow.

As a result the TSLogger is not initialized correctly because it's static and the handler is not associated with it. 

https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaspic/tssv/config/TSAuthConfigProviderServlet.java#L59

Removing eager init here
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaspic/tssv/config/TSAuthConfigProviderServlet.java#L59

Should let the constructor to do the proper init.

The TSAuthConfigProvider is fine but TSAuthConfigProviderStandalone does not seem to be either.

**Comment by scottmarlow** [comment]
@jeanouii Please do supply the required information mentioned in the TCK process document:

> Challenges MUST be filed via the specification project’s issue tracker using the label challenge and include the following information:
> 
>     The relevant specification version and section number(s)
> 
>     The coordinates of the challenged test(s)
> 
>     The exact TCK version
> 
>     The implementation being tested, including name and company
> 
>     A full description of why the test is invalid and what the correct behavior is believed to be
> 
>     Any supporting material; debug logs, test output, test logs, run scripts, etc.
>
