### ISSUE TITLE
Prepare new Authentication TCK

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/authentication#150]
1. [x]  Copying tests to /tck in this project.
2. [x] Changing package names to `ee.jakarta.tck`
3. [x] Adding (additional) comments to test 
4. [x] Incorporating the existing TCK from https://github.com/eclipse-ee4j/jakartaee-tck
5. [x] Creating single zip distribution of the entire TCK
6. [x] Create / update guide / docs on how to run the TCK
5. [ ] Adding example to run TCK as dependency from Maven into your own pom.
    (see https://github.com/piranhacloud/piranha/tree/current/external/tck/jwt)

**Comment by starksm64** [comment]
What is the subtree under https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests for the authentication tests?

**Comment by arjantijms** [comment]
@starksm64 that is https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/jaspic

**Comment by arjantijms** [comment]
Note we don't necessarily need to have the Authentication (JASPIC) sources transferred to this repo. We could do that at a later date too.

**Comment by alwin-joseph** [comment]
> Note we don't necessarily need to have the Authentication (JASPIC) sources transferred to this repo. We could do that at a later date too. 

Does this mean the existing JASPIC TCK need not be run or to use https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/tests/tck/authentication/pom.xml with modifications to integrate the existing TCK from https://github.com/eclipse-ee4j/jakartaee-tck. 
If we are to incorporate the existing TCK in this way, the bundle will have to be hosted at a location so that it can be run from the new TCK.

**Comment by arjantijms** [comment]
>  to use https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/tests/tck/authentication/pom.xml with modifications to integrate the existing TCK from https://github.com/eclipse-ee4j/jakartaee-tck.

That option. The existing TCK would then be run like https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/tests/tck/authentication/pom.xml

> If we are to incorporate the existing TCK in this way, the bundle will have to be hosted at a location so that it can be run from the new TCK.

Indeed, it's not super ideal as we'd be hosting two bundles then, but with only days to go, maybe attempting to transfer the source at this point is too time consuming and we'd better invest that time in making sure the Faces and Security TCKs are fully up and running.

**Comment by starksm64** [comment]
@arjantijms I see @alwin-joseph created a PR to kickstart the userguide. I can take a look at verifying it once merged.

**Comment by starksm64** [comment]
The TCK userguide needs to be updated to reflect the use of maven/arquillian. I'm working on that.

**Comment by arjantijms** [comment]
@starksm64 thanks!

**Comment by starksm64** [comment]
#156 provides an adequate userguide and updates the TCK zip to meet the requirements

**Comment by arjantijms** [comment]
Thanks @starksm64 

The TCK is now available from https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-authentication-tck-3.0.0-dist.zip and should be sufficient for ratification.

The example for another server can be done at a later time.

**Comment by alwin-joseph** [comment]
The https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-authentication-tck-3.0.0.zip  is the old TCK built from jakartaee-tck . 
The https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-authentication-tck-3.0.0-dist.zip is the final official TCK.

The old tck is executed(against glassfish only for now) from final TCK using the tck runner script at tck/old-tck-runner/pom.xml.  

The final/official TCK should be used for ballot.

**Comment by alwin-joseph** [comment]
@arjantijms Is the new TCK run job created in authentication Jenkins instance? If possible please share the result where the new tests and old tck are passing.

cc @scottmarlow

**Comment by arjantijms** [comment]
Hi,

The TCK archive is build on ci.eclipse.org/es, since during the weekend
that one had upload rights.

The created archive is unpacked executed via ci.eclipse.org/authentication

See:

https://ci.eclipse.org/authentication/job/2_authentication_run_tck_against_staged_build
<https://ci.eclipse.org/authentication/job/2_authentication_run_tck_against_staged_build/configure>

Kind regards,
Arjan Tijms

**Comment by arjantijms** [comment]
The new authentication TCK is there! Thanks to everyone involved. We have some more enhancements to do, but we can track that work in a 4.0.1 service release issue.
