### ISSUE TITLE
Finalize Jakarta Authentication 3.0

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/authentication#164]
Please complete these steps to finalize the release:

- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from Draft to Final.
 approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.
- [x]  merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
API available here: https://repo1.maven.org/maven2/jakarta/authentication/jakarta.authentication-api/3.0.0/

**Comment by arjantijms** [comment]
No schema's needed to be updated.

**Comment by arjantijms** [comment]
The issue can be closed, everything has been done, and the release is live :)
