### ISSUE TITLE
Question about using authentication

### ISSUE THREAD

**Issue by LudovicLachance** [jakartaee/authentication#195]
I would like to ask if someone have an example that can be viewed about using this to create a simple login/logout/register java Jakarta app with a in memory IdentityStore.

I cannot find any example using this without third party code hiding the logic.

I am using Jakarta RESTful Web Services to make my controller, I can specify the roles allowed, but there is no way to redirect to a login page if a user is not logged in.

**Comment by arjantijms** [comment]
That would actually be a question for Jakarta Security (Jakarta Authenticaton is the lower level SPI used for authentication concerns).

You can find a number of examples with explanation here: https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/security/security.html

**Comment by LudovicLachance** [comment]
Thanks.
