### ISSUE TITLE
No tag for TCK 3.1.0 release

### ISSUE THREAD

**Issue by markt-asf** [jakartaee/authentication#218]
It should be possible to recreate releases from tags but I can find the tag for the most recent TCK release (3.1.0).

**Comment by arjantijms** [comment]
Thanks again Mark! Luckily we recorded the git rev in the CI. It's

https://github.com/jakartaee/authentication/commit/66fe1ab8bb472537d0278f8ce648a2503bd1fa3d

I'll create a tag for it.

Note to self and other team members: we need to make sure the CI creates this tag

**Comment by arjantijms** [comment]
Tag is now created here: https://github.com/jakartaee/authentication/releases/tag/3.1.0-RELEASE-tck

I tried to set the date correctly, but that part didn't work (or I did it wrong).
